CXX 	= cl 

all:net495.exe \
	net496.exe \
	net497.exe \
	net498.exe \
	net499.exe \
	net500.exe \
	net501.exe \
	net502.exe \
	net503.exe \
#	net503g.exe \
	net504.exe \
#	net504g.exe \
	net505.exe \
	net506.exe \
#	net506g.exe \
	net507.exe \
	net508.exe \
	net509.exe \
	net510.exe \
	net512.exe \
	net513.exe \
	net514.exe \
	net515.exe \
	net516.exe \
	net517.exe \
	net518.exe \
	net519.exe \
	net520.exe \
	net521.exe \
	net522.exe \
	net523.exe \
	net524.exe \
	net525.exe \
	net526.exe \
	net527.exe \
	net528.exe \
	net529.exe \
	net530.exe \
	net531.exe \
	net532.exe \
	net533.exe \
	net534.exe 

	 

clean: 
	del *.exe *.obj

.cpp.exe:
	$(CXX) /nologo /EHsc $< ws2_32.lib

