all:
	cd "第1章 基礎の極意" & nmake & cd ..
	cd "第2章 文法の極意" & nmake & cd ..
	cd "第3章 標準関数の極意" & nmake & cd ..
	cd "第4章 STLの極意" & nmake & cd ..
	cd "第5章 通信の極意" & nmake & cd ..
	cd "第6章 CppUnitの極意" & nmake & cd ..
clean:
	cd "第1章 基礎の極意" & nmake clean & cd ..
	cd "第2章 文法の極意" & nmake clean & cd ..
	cd "第3章 標準関数の極意" & nmake clean & cd ..
	cd "第4章 STLの極意" & nmake clean & cd ..
	cd "第5章 通信の極意" & nmake clean & cd ..
	cd "第6章 CppUnitの極意" & nmake clean & cd ..
	

	
