all:
	cd ch01; make; cd ..;
	cd ch02; make; cd ..;
	cd ch03; make; cd ..;
	cd ch04; make; cd ..;
	cd ch05; make; cd ..;
	cd ch06; make; cd ..;
clean:
	cd ch01; make clean; cd ..;
	cd ch02; make clean; cd ..;
	cd ch03; make clean; cd ..;
	cd ch04; make clean; cd ..;
	cd ch05; make clean; cd ..;
	cd ch06; make clean; cd ..;
	
	
