CC		= gcc
CXX 	= g++ 
CXXFLAGS = -std=c++14 -Wformat=0 

ALL = func154 \
	func155 \
	func156 \
	func157 \
	func158 \
	func159 \
	func160 \
	func161 \
	func162 \
	func163 \
	func164 \
	func165 \
	func166 \
	func167 \
	func168 \
	func169 \
	func170 \
	func171 \
	func172 \
	func173 \
	func174 \
	func175 \
	func176 \
	func177 \
	func178 \
	func179 \
	func180 \
	func181 \
	func182 \
	func183 \
	func184 \
	func184a \
	func184b \
	func185 \
	func186 \
	func187 \
	func188 \
	func189 \
	func190 \
	func192 \
	func193 \
	func194 \
	func195 \
	func196 \
	func198 \
	func201 \
	func202 \
	func203 \
	func204 \
	func205 \
	func206 \
	func207 \
	func208 \
	func209 \
	func210 \
	func211 \
	func212 \
	func213 \
	func214 \
	func215 \
	func216 \
	func217 \
	func218 \
	func219 \
	func220 \
	func221 \
	func222 \
	func223 \
	func224 \
	func225 \
	func226 \
	func227 \
	func228 \
	func229 \
	func230 \
	func231 \
	func232 \
	func233 \
	func234 \
	func235 \
	func236 \
	func237 \
	func238 \
	func239 \
	func240 \
	func241 \
	func242 \
	func243 \
	func244 \
	func245 \
	func246 \
	func247 \
	func248 \
	func249 \
	func250 \
	func251 \
	func252 \
	func253 \
	func254 \
	func255 \
	func256 \
	func257 \
	func258 \
	func259 \
	func260 \
	func261 \
	func262 \
	func263 \
	func264 \
	func265 \
	func266 \
	func267 \
	func279 \
	func280 \
	func281 \
	func282 \
	func283 \
	func285 \
	func286 \
	func287 \
	func288 

all: $(ALL)

clean: 
	$(RM) *.o $(ALL) 
 
.SUFFIXES: .o .cpp .c

.c.o:
	$(CC) -c $<
.cpp.o:
	$(CXX) $(CXXFLAGS) -c $<
.c:
	$(CC) -o $@ $<
.cpp:
	$(CXX) $(CXXFLAGS) -o $@ $<
	
