CXX 	= cl 

all:grm008.exe \
	grm009.exe \
	grm010.exe \
	grm011.exe \
	grm012.exe \
	grm013.exe \
	grm014.exe \
	grm015.exe \
	grm016.exe \
	grm017.exe \
	grm018.exe \
	grm019.exe \
	grm020.exe \
	grm021.exe \
	grm022.exe \
	grm023.exe \
	grm024.exe \
	grm025.exe \
	grm026.exe \
	grm028.exe \
	grm029.exe \
	grm030.exe \
	grm031.exe \
	grm032.exe \
	grm033.exe \
	grm034.exe \
	grm035.exe \
	grm036.exe \
	grm037.exe \
	grm038.exe \
	grm039.exe \
	grm040.exe \
	grm041.exe \
	grm042.exe \
	grm043.exe \
	grm044.exe \
	grm045.exe \
	grm046.exe \
	grm047.exe \
	grm048.exe \
	grm049.exe \
	grm050.exe \
	grm051.exe \
	grm052.exe \
	grm053.exe \
	grm054.exe \
	grm055.exe \
	grm056.exe \
	grm057.exe \
	grm058.exe \
	grm061.exe \
	grm062.exe \
	grm063.exe \
	grm064.exe \
	grm065.exe \
	grm066.exe \
	grm067.exe \
	grm068.exe \
	grm069.exe \
	grm070.exe \
	grm071.exe \
	grm072.exe \
	grm073.exe \
	grm074.exe \
	grm075.exe \
	grm076.exe \
	grm077.exe \
	grm078.exe \
	grm079.exe \
	grm080.exe \
	grm081.exe \
	grm083.exe \
	grm084.exe \
	grm085.exe \
	grm086.exe \
	grm087.exe \
	grm088.exe \
	grm089.exe \
	grm090.exe \
	grm091.exe \
	grm092.exe \
	grm093.exe \
	grm094.exe \
	grm095.exe \
	grm096.exe \
	grm097.exe \
	grm098.exe \
	grm099.exe \
	grm100.exe \
	grm101.exe \
	grm102.exe \
	grm103.exe \
	grm104.exe \
	grm105.exe \
	grm106.exe \
	grm108.exe \
	grm109.exe \
	grm110.exe \
	grm111.exe \
	grm112.exe \
	grm113.exe \
	grm114.exe \
	grm115.exe \
	grm116.exe \
	grm117.exe \
#	grm118.exe \
	grm119.exe \
	grm120.exe \
	grm121.exe \
	grm122.exe \
	grm123.exe \
	grm124.exe \
	grm125.exe \
	grm126.exe \
	grm127.exe \
	grm129.exe \
	grm130.exe \
	grm131.exe \
	grm132.exe \
	grm133.exe \
	grm134.exe \
	grm135.exe \
	grm136.exe \
	grm137.exe \
	grm138.exe \
	grm139.exe \
	grm140.exe \
	grm141.exe \
	grm142.exe \
	grm143.exe \
	grm144.exe \
	grm145.exe \
	grm146.exe \
	grm148.exe \
	grm149.exe \
	grm150.exe \
	grm151.exe \
	grm152.exe 


grm088.exe: grm088.cpp grm088sub.cpp
	$(CXX) /EHsc /Fe$@ grm088.cpp grm088sub.cpp
grm103.exe: grm103.cpp grm103sub.cpp
	$(CXX) /EHsc /Fe$@ grm103.cpp grm103sub.cpp

clean: 
	del *.exe *.obj

.cpp.exe:
	$(CXX) /nologo /EHsc $<

